### ISSUE TITLE
removal

### ISSUE THREAD

**Issue by Akrek** [LeGhast/Miniaturise#3]
hi, I created a thumbnail and in an attempt to deal with the commands, I created 2 thumbnails at once, but when trying to delete them, only 1 was deleted, and trying to figure out how to delete it, I created 1 more thumbnail that does not want to be deleted, I tried to reinstall the plugin on the server, but they all There are still some left. Please help me to delete them
![2024-04-16_11 25 53](https://github.com/GhastCraftHD/Miniaturise/assets/133111660/74a7212d-ddb1-4593-9620-c470fb530f7a)

**Comment by Akrek** [comment]
I found a command to remove miniatures: /kill @e[type=minecraft:block_display, distance=~, sort=nearest]
I also won't delete this question so that the creator will pay attention to it and maybe others will need it.

**Comment by GhastCraftHD** [comment]
To delete a placed miniature, just select the region, that contains the miniature as usually, and use /mselect to select it. After that you can delete it. This is also explained in further detail in the documentation under the tutorial section. I would not recommend to use the command, because it could easily delete parts of other miniatures aswell.
![](https://github.com/GhastCraftHD/Miniaturise/assets/70332776/7efe499f-6279-46be-a345-9b623052b30b)

**Comment by Robsel** [comment]
There is still a "problem", that if you scale the mini to be bigger than 1, that you have to completely capture the "miniature" with your selection, else it cant find it. I accidently put 2 in the scale factor and couldnt remove it, until i selected an area that was bigger than the (really big) miniature. great mod, just wanted it mentioned

**Comment by GhastCraftHD** [comment]
First of all, thank you :)

If you make your miniature very big, you'll need to capture its entire extent to select it again. But I wouldn't call this a problem, because how else would you want to select it?

Before unselecting you can always use the adjuster interface and tool to resize it again, if you accidentally made it to big with the command.

btw, I don't kown if that was clear, but after pasting a miniature you automatically select that one. So after placing you can directly remove it and adjust it
