### ISSUE TITLE
Hologram Removal

### ISSUE THREAD

**Issue by MVGrandy** [LeGhast/Miniaturise#6]
![2024-08-31_23 58 01](https://github.com/user-attachments/assets/dec2b4fe-59e6-4ca6-9c0f-187f20823059)

Was testing out the plugin and cannot get rid of this test hologram. The second on I had I was able to use the /mremove command but the program does not recognize the hologram existing but obviously its still there. Any input to help get rid of this would be a lot of help. I like the plugin just don't want this eye sore on my spawn.

Thanks!

**Comment by GhastCraftHD** [comment]
You could't remove the first one because it was no longer in your miniature clipboard. You basically have two clipboards, one for a miniature that you can paste and one for the last pasted miniature. When you place the second one you moved the first from your clipboard. You should be able to select the first one though. 

When you select an area by chosing two positions and then executing /mselect you not only select the area as a placable miniature but also every miniature that is within this area. So you basically move all miniatures in the area in your clipboard as one big miniature. And you should be able to remove that one then by using /mremove

Let me know, if that fixed your issue

**Comment by MVGrandy** [comment]
Hello Ghast! First-off, I appreciate your speedy response!

 I had walk though that process before as laid out in documentation but it seems like its still not even detecting the "display blocks" are even there. Here is that process below!
 
![RegionSelected](https://github.com/user-attachments/assets/1764e933-d7f7-4cbe-b860-50028f010c48)
![RegionSelectedComplete](https://github.com/user-attachments/assets/2f7b3197-effd-453c-ae5b-8c878081bc4c)
![mRemove_fail](https://github.com/user-attachments/assets/74813d54-bc05-4802-a545-226e45dabd13)

I also tried selecting the "display blocks" themselves by expanding the region over it but that exceeds the 1500 limit. My server is a 1.20.4 Vanilla with plugins and I am running Miniaturise-2.4.5.jar .

Thank you Ghast again and appreciate your help.

**Comment by GhastCraftHD** [comment]
You can temporarily adjust the block limit in the config file of the plugin or you can use a command to delete all holograms.

The command would be: /kill @e[type=block_display] but beware, that this will delete all miniatures and block displays

**Comment by MVGrandy** [comment]
Success!!

I had tried the /kill command before to no affect seen below. 

![ErrorNoPlayer](https://github.com/user-attachments/assets/3a652ef4-1182-4d2f-9145-b624ee8a3c84)

But the real fix was going into the config and upping the selector limit to fit the needed volume.

You're the best Ghast! Have a great day!

Edit: Success!
![2024-09-01_11 26 25](https://github.com/user-attachments/assets/a1b2e2a2-bf19-4d1f-a921-0d580f38816e)
